### ISSUE TITLE
Gen7 wild Displaying wrong results

### ISSUE THREAD

**Issue by Unknown-Warrior** [Admiral-Fish/3DSTimeFinder#12]
Was searching for wild results in the 200,000-300,000 frame range, got results that were actually 200k frames earlier than projected:

[3DS Time Finder results](https://i.imgur.com/aRzlztF.pngl)

[Actual results 1](https://i.imgur.com/GiiihyL.png) [Actual results 2](https://i.imgur.com/oZJ0Gt2.png)

**Comment by Admiral-Fish** [comment]
It isn't intended to be an exact match to 3dsrngtool. I don't account for blinks at all, this tool has always been intended to get you close enough then use 3dsrngtool for the blink accounting
