### ISSUE TITLE
.exe file

### ISSUE THREAD

**Issue by Vindicator-21** [Admiral-Fish/3DSTimeFinder#2]
Hi.

I'm completely illiterate in programming/computer science. Could you please provide a zip that contains an .exe for the 3DS Time Finder in the releases section? Or is it still a work in progress?

I also noticed that the CitraRNG 3.0.0 script doesn't display the stats of my pokemon in my party or the wild for gen 7, noted by the following line everytime I try to update it:

![CitraScript](https://user-images.githubusercontent.com/59811916/72286557-5cf41500-3613-11ea-97f5-aeda722335ba.png)

The initial seed for gen 6/7 work fine, so do the displays for egg parents. Playing on USUM v1.2

If you could help out I'd really appreciate it.  Thanks!

**Comment by Admiral-Fish** [comment]
Try entirely removing and re-downloading CitraRNG. If you still have issues then open an issue in the appropriate repo.
