### ISSUE TITLE
PIDs aren't displayed despite being searched for (since that would be the only way to scope out a possible Shiny)

### ISSUE THREAD

**Issue by Acumenium** [Admiral-Fish/3DSTimeFinder#3]
I know it's not as important to know PIDs as it used to be due to them not being tied to IVs but if we are able to import "square Shinies" into Sword and Shield (we currently do not know this yet) it could be useful to know what PIDs we are finding so we can try and get proper IDs/SIDs in order for them.

**Comment by Admiral-Fish** [comment]
Will consider when home is actually released

**Comment by Acumenium** [comment]
Would it be complicated to add a PID display? It's already looking for them anyway so it's not like you're doing much more to display what it already finds.

**Comment by Acumenium** [comment]
Well, Pokemon Home is out. You can indeed import Square Shinies. So... can we have PIDs display? Please?

**Comment by Djuraaaa** [comment]
Yeah, there was also an update to 3DSRNGTool that supports RNGing for square shinies.

**Comment by Acumenium** [comment]
There's frankly little reason not to display the PIDs. The only way it is able to locate shinies is because it is looking for PIDs in the first place to match your TSV with.
