### ISSUE TITLE
When searching for Pokemon, the % in the "searched" search bar doesn't update unless cancelled, or finished

### ISSUE THREAD

**Issue by Acumenium** [Admiral-Fish/3DSTimeFinder#4]
I had it running for an hour and I thought it wasn't doing anything, since it didn't find any results yet and was at 0%.

Hit Cancel and it seems it actually WAS moving, but it never updated.

**Comment by Admiral-Fish** [comment]
Either the version or commit hash would be helpful that you are using.

**Comment by Acumenium** [comment]
https://github.com/Admiral-Fish/3DSTimeFinder/releases/tag/v1.0.0

There's literally only one version? What exactly are you asking for?

**Comment by Admiral-Fish** [comment]
Can't replicate. Please be more specific in which searcher you were using and search settings

**Comment by Acumenium** [comment]
All search menus are like this. They stay at 0% and don't update at all unless the search finishes.

**Comment by Admiral-Fish** [comment]
This provides me very little additional information. Unless you can provide additional information for me to troubleshoot I will have to close this issue.
