### ISSUE TITLE
Last commit Gen 7 Calibrator can't handle big limits research

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/3DSTimeFinder#5]
In last commit, Gen 7 Calibrator crashes if Tick Range is 1000000+. Last release handle it perfectly instead

**Comment by Admiral-Fish** [comment]
Please provide exact details of settings

**Comment by Real96** [comment]
![unknown](https://user-images.githubusercontent.com/20956021/100479848-b8c27200-30ef-11eb-8268-15380cf80cc8.png)
This settings make the app crash

**Comment by Admiral-Fish** [comment]
Fixed by 13dc787
